package br.ifpe.serverless.ApplicationServerless.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.google.gson.Gson;

public class PersonRequest {
    
	
	private String id ;
    private String medico;
    private int CRM;
    private String hospital ;
    private String CNPJ ;
    private String paciente ;
    private String convenio ;
    private  String acomodacao ;
    private String procedimento ;
    
    public PersonRequest(){
    
    }
    
    public PersonRequest(String id,String medico,int CRM,String hospital,String CNPJ,String convenio , String paciente,String acomodacao,String procedimento ){
    	this.id = id;
    	this.medico = medico;
    	this.CRM =CRM;
    	this.hospital = hospital;
    	this.CNPJ = CNPJ;
    	this.paciente = paciente;
    	this.convenio = convenio;
    	this.acomodacao = acomodacao;
    	this.procedimento = procedimento;
    
    }
    public PersonRequest(String json) {
    	Gson gson = new Gson();
    	PersonRequest registro = gson.fromJson(json, PersonRequest.class);
    	this.id = registro.id;
    	this.medico = registro.medico;
    	this.CRM = registro.CRM;
    	this.hospital = registro.hospital;
    	this.CNPJ = registro.CNPJ;
    	this.paciente = registro.paciente;
    	this.convenio = registro.convenio;
    	this.acomodacao = registro.acomodacao;
    	this.procedimento = registro.procedimento;
    	
    	
    }
    
    public String toString() {
    	return new Gson().toJson(this);
    }
    
    
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
    
	public String getMedico() {
		return medico;
	}
	public void setMedico(String medico) {
		this.medico = medico;
	}
	public int getCRM() {
		return CRM;
	}
	public void setCRM(int cRM) {
		CRM = cRM;
	}
	public String getHospital() {
		return hospital;
	}
	public void setHospital(String hospital) {
		this.hospital = hospital;
	}
	public String getCNPJ() {
		return CNPJ;
	}
	public void setCNPJ(String cNPJ) {
		CNPJ = cNPJ;
	}
	public String getPaciente() {
		return paciente;
	}
	public void setPaciente(String paciente) {
		this.paciente = paciente;
	}
	public String getConvenio() {
		return convenio;
	}
	public void setConvenio(String convenio) {
		this.convenio = convenio;
	}
	public String getAcomodacao() {
		return acomodacao;
	}
	public void setAcomodacao(String acomodacao) {
		this.acomodacao = acomodacao;
	}
	public String getProcedimento() {
		return procedimento;
	}
	public void setProcedimento(String procedimento) {
		this.procedimento = procedimento;
	}

	
    
}
